# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

# Sharable configurations
default_config: &default_config
  docker:
    - image: circleci/node:8.12
  working_directory: ~/repo
restore_cache: &restore_cache
  keys:
    - v1-dependencies-{{ checksum "package.json" }}
    - v1-dependencies-
save_cache: &save_cache
  paths:
    - node_modules
  key: v1-dependencies-{{ checksum "package.json" }}

# Jobs
version: 2
jobs:
  test:
    <<: *default_config
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: yarn
      - save_cache: *save_cache
      - run: yarn test
  build:
    <<: *default_config
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: yarn
      - save_cache: *save_cache
      - run: yarn build

# Workflows
workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build
